### ISSUE TITLE
[BUG] Attempting to use oc v4.7, which is not available

### ISSUE THREAD

**Issue by pdufault** [redhat-actions/oc-installer#14]
### Version
redhat-actions/oc-installer@v1

### Describe the bug
```
Run redhat-actions/oc-installer@v1
  with:
    oc_version: 4.7.0
Installing oc version 4.7
Found oc version 4.7 at https://mirror.openshift.com/pub/openshift-v4/clients/oc/4.7/linux/oc.tar.gz
Downloading oc from https://mirror.openshift.com/pub/openshift-v4/clients/oc/4.7/linux/oc.tar.gz ...
Error: Error: Unexpected HTTP response: 404-->
```

Is there a reason why this Github action is pointed at this particular location of oc binaries? At https://mirror.openshift.com/pub/openshift-v4/clients/oc/$__DEPRECATED_LOCATION__PLEASE_READ__.txt it indicates this is a deprecated location and to use https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/

**Comment by tetchel** [comment]
I suppose that was the correct location when this action was originally written last year.

We can change the directory to `ocp`. In the meantime, I suggest you use https://github.com/redhat-actions/openshift-tools-installer which can definitely install oc 4.7 and uses the `ocp` directory already.

**Comment by pdufault** [comment]
Thank you for the information!  Is this information documented somewhere, and I missed it? 😅

**Comment by tetchel** [comment]
It's in the README here, but that change hasn't been published to the marketplace. I'm taking this as a note to improve this documentation a little.

![image](https://user-images.githubusercontent.com/8888438/120515446-4e3f0700-c39c-11eb-8e00-1f13085143d2.png)

**Comment by tetchel** [comment]
I looked into changing to the `ocp` directory, but it has a very different file structure which would result in having to rewrite most of this action.

If you want to use oc 4.7.0, you must use openshift-tools-installer.

I have increased the visibility of the note in the readme in https://github.com/redhat-actions/oc-installer/commit/6997548adb57c94cb4b4fd6a323a59612dae5a8a
